spring.application.name=dept-tree-module
server.port=8081
#debug=true
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#### kafka ####
# 告訴應用程式應該連接到哪一個或哪幾個 Kafka broker 來發送和接收消息
spring.kafka.bootstrap-servers=localhost:9092


## Producer 配置
# 發生錯誤，重送次數
spring.kafka.producer.retries=5 
spring.kafka.producer.batch-size=16384
spring.kafka.producer.buffer-memory=33554432
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1

## Consumer 配置
spring.kafka.consumer.auto-commit-interval=1000
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.group-id=group.mail
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.session.timeout.ms=15000

## Listener 配置
spring.kafka.listener.concurrency=5
#spring.kafka.listener.ack-mode=manual-immediate
spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.ack-mode=record
logging.level.org.springframework.kafka=DEBUG
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka.listener.KafkaMessageListenerContainer=DEBUG
