spring.application.name=tenant-service
server.port=8082

# ==========================================
# PostgreSQL 配置
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/iam_tenant_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==========================================
# JPA / Hibernate 配置
# ==========================================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
